// Esquema genérico (8 tablas) descrito una vez con tipos abstractos y renderizado por dialecto SQL,
// MongoDB (JS) y Redis (comandos). También renderiza los seeds a partir de un Dataset.
import { markerHeader } from '../engine/synthetic-mx.mjs';

export const TABLES = ['usuarios', 'clientes', 'direcciones', 'cuentas_bancarias', 'pedidos', 'facturas', 'pagos', 'auditoria'];

/** Columnas: [nombre, tipoAbstracto, opciones]. Tipos: id, fk:<tabla>, int, bool, date, timestamp, text, decimal, char(n), varchar(n). */
export const COLUMNS = {
  usuarios: [['id', 'id'], ['email', 'varchar(160)', { unique: true, notNull: true }], ['nombre', 'varchar(120)'], ['hash_password', 'varchar(255)'], ['rol', 'varchar(30)'], ['activo', 'bool'], ['creado_en', 'timestamp']],
  clientes: [['id', 'id'], ['usuario_id', 'fk:usuarios'], ['nombre', 'varchar(120)'], ['apellido_paterno', 'varchar(80)'], ['apellido_materno', 'varchar(80)'], ['sexo', 'char(1)'], ['fecha_nacimiento', 'date'], ['rfc', 'char(13)'], ['curp', 'char(18)'], ['nss', 'char(11)'], ['telefono', 'varchar(20)'], ['email', 'varchar(160)'], ['creado_en', 'timestamp']],
  direcciones: [['id', 'id'], ['cliente_id', 'fk:clientes'], ['calle', 'varchar(120)'], ['numero', 'varchar(10)'], ['colonia', 'varchar(120)'], ['cp', 'char(5)'], ['municipio', 'varchar(120)'], ['estado', 'varchar(80)'], ['pais', 'char(2)']],
  cuentas_bancarias: [['id', 'id'], ['cliente_id', 'fk:clientes'], ['banco', 'varchar(60)'], ['clabe', 'char(18)'], ['tarjeta_prueba', 'varchar(19)'], ['tarjeta_ultimos4', 'char(4)'], ['activa', 'bool']],
  pedidos: [['id', 'id'], ['cliente_id', 'fk:clientes'], ['folio', 'varchar(20)'], ['total', 'decimal'], ['moneda', 'char(3)'], ['estatus', 'varchar(20)'], ['creado_en', 'timestamp']],
  facturas: [['id', 'id'], ['pedido_id', 'fk:pedidos'], ['uuid_fiscal', 'char(36)'], ['rfc_receptor', 'char(13)'], ['subtotal', 'decimal'], ['iva', 'decimal'], ['total', 'decimal'], ['emitida_en', 'timestamp']],
  pagos: [['id', 'id'], ['factura_id', 'fk:facturas'], ['metodo', 'varchar(20)'], ['monto', 'decimal'], ['referencia', 'varchar(40)'], ['pagado_en', 'timestamp']],
  auditoria: [['id', 'id'], ['entidad', 'varchar(40)'], ['entidad_id', 'int'], ['accion', 'varchar(20)'], ['usuario_id', 'fk:usuarios'], ['detalle', 'text'], ['creado_en', 'timestamp']],
};

/* ----------------------------------- tipos por dialecto ----------------------------------- */

const TYPES = {
  postgres: { id: 'BIGSERIAL PRIMARY KEY', fk: 'BIGINT', int: 'INTEGER', bool: 'BOOLEAN', date: 'DATE', timestamp: 'TIMESTAMPTZ DEFAULT now()', text: 'TEXT', decimal: 'NUMERIC(12,2)', char: (n) => `CHAR(${n})`, varchar: (n) => `VARCHAR(${n})` },
  mysql: { id: 'BIGINT AUTO_INCREMENT PRIMARY KEY', fk: 'BIGINT', int: 'INT', bool: 'TINYINT(1)', date: 'DATE', timestamp: 'DATETIME DEFAULT CURRENT_TIMESTAMP', text: 'TEXT', decimal: 'DECIMAL(12,2)', char: (n) => `CHAR(${n})`, varchar: (n) => `VARCHAR(${n})` },
  mssql: { id: 'BIGINT IDENTITY(1,1) PRIMARY KEY', fk: 'BIGINT', int: 'INT', bool: 'BIT', date: 'DATE', timestamp: 'DATETIME2 DEFAULT SYSUTCDATETIME()', text: 'NVARCHAR(MAX)', decimal: 'DECIMAL(12,2)', char: (n) => `CHAR(${n})`, varchar: (n) => `NVARCHAR(${n})` },
  oracle: { id: 'NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY', fk: 'NUMBER(19)', int: 'NUMBER(10)', bool: 'NUMBER(1)', date: 'DATE', timestamp: 'TIMESTAMP DEFAULT SYSTIMESTAMP', text: 'CLOB', decimal: 'NUMBER(12,2)', char: (n) => `CHAR(${n})`, varchar: (n) => `VARCHAR2(${n} CHAR)` },
  sqlite: { id: 'INTEGER PRIMARY KEY AUTOINCREMENT', fk: 'INTEGER', int: 'INTEGER', bool: 'INTEGER', date: 'TEXT', timestamp: 'TEXT DEFAULT CURRENT_TIMESTAMP', text: 'TEXT', decimal: 'NUMERIC', char: (n) => `TEXT`, varchar: (n) => `TEXT` },
};

export const SQL_DIALECTS = Object.keys(TYPES);

function sqlType(dialect, abstract) {
  const t = TYPES[dialect];
  const m = /^(char|varchar)\((\d+)\)$/.exec(abstract);
  if (m) return t[m[1]](Number(m[2]));
  if (abstract.startsWith('fk:')) return t.fk;
  return t[abstract] ?? abstract;
}

function columnDef(dialect, [name, abstract, opts = {}]) {
  let def = `${name} ${sqlType(dialect, abstract)}`;
  if (opts.notNull) def += ' NOT NULL';
  if (opts.unique) def += ' UNIQUE';
  if (abstract.startsWith('fk:')) def += ` REFERENCES ${abstract.slice(3)}(id)`;
  return def;
}

/** Sentencia CREATE TABLE para una tabla y dialecto (idempotente donde el motor lo permite). */
export function createTableSql(dialect, table) {
  const cols = COLUMNS[table].map((c) => '  ' + columnDef(dialect, c)).join(',\n');
  const body = `(\n${cols}\n)`;
  if (dialect === 'mssql') return `IF OBJECT_ID('${table}', 'U') IS NULL\nCREATE TABLE ${table} ${body};`;
  if (dialect === 'oracle') return `CREATE TABLE ${table} ${body};`; // Oracle 23c: IF NOT EXISTS existe pero aquí el script corre una sola vez
  if (dialect === 'mysql') return `CREATE TABLE IF NOT EXISTS ${table} ${body} ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`;
  return `CREATE TABLE IF NOT EXISTS ${table} ${body};`;
}

/** Esquema genérico completo (8 tablas + índices) para un dialecto SQL. */
export function renderSchema(dialect) {
  if (!TYPES[dialect]) throw new Error(`dialecto desconocido: ${dialect}`);
  const lines = [`-- bot-secure: esquema genérico de pruebas (${dialect}). Tablas: ${TABLES.join(', ')}.`, '-- Generado; regenerar con: bot-secure db init --generic', ''];
  if (dialect === 'mysql') lines.push('SET NAMES utf8mb4;', '');
  for (const t of TABLES) lines.push(createTableSql(dialect, t), '');
  const idx = (name, table, col) => (dialect === 'mssql'
    ? `IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = '${name}') CREATE INDEX ${name} ON ${table}(${col});`
    : dialect === 'oracle' || dialect === 'mysql' ? `CREATE INDEX ${name} ON ${table}(${col});` : `CREATE INDEX IF NOT EXISTS ${name} ON ${table}(${col});`);
  lines.push(idx('ix_clientes_rfc', 'clientes', 'rfc'), idx('ix_direcciones_cp', 'direcciones', 'cp'), idx('ix_pedidos_cliente', 'pedidos', 'cliente_id'), idx('ix_auditoria_entidad', 'auditoria', 'entidad, entidad_id'), '');
  return lines.join('\n');
}

/* --------------------------------------- seeds SQL --------------------------------------- */

const esc = (s) => String(s).replace(/'/g, "''");

/** Literal SQL para un valor según su tipo abstracto y dialecto. */
export function sqlLiteral(dialect, abstract, value) {
  if (value === null || value === undefined) return 'NULL';
  if (abstract === 'bool') return dialect === 'postgres' ? (value ? 'TRUE' : 'FALSE') : (value ? '1' : '0');
  if (abstract === 'id' || abstract === 'int' || abstract.startsWith('fk:') || abstract === 'decimal') return String(value);
  if (abstract === 'date') return dialect === 'mssql' || dialect === 'sqlite' ? `'${value}'` : `DATE '${value}'`;
  if (abstract === 'timestamp') return dialect === 'mssql' || dialect === 'sqlite' ? `'${value}'` : `TIMESTAMP '${value}'`;
  const q = `'${esc(value)}'`;
  return dialect === 'mssql' && /^(varchar|text)/.test(abstract) ? 'N' + q : q;
}

function insertSql(dialect, table, row) {
  const cols = COLUMNS[table];
  return `INSERT INTO ${table} (${cols.map((c) => c[0]).join(', ')}) VALUES (${cols.map((c) => sqlLiteral(dialect, c[1], row[c[0]])).join(', ')});`;
}

/**
 * Seeds SQL idempotentes: cabecera con marcador, borrado en orden inverso de FK, INSERTs con id explícito
 * y sincronización de secuencias/identidad al final.
 */
export function renderSeedsSql(dialect, dataset, { seed, rows } = {}) {
  const out = [markerHeader('--', { seed, rows }), `-- Datos SINTÉTICOS es_MX generados por bot-secure (semilla ${seed ?? '?'}). No corresponden a personas reales.`, ''];
  if (dialect === 'mysql') out.push('SET NAMES utf8mb4;', 'SET FOREIGN_KEY_CHECKS = 0;');
  if (dialect === 'postgres') out.push('BEGIN;');
  for (const t of [...TABLES].reverse()) out.push(`DELETE FROM ${t};`);
  out.push('');
  for (const t of TABLES) {
    if (dialect === 'mssql') out.push(`SET IDENTITY_INSERT ${t} ON;`);
    for (const row of dataset[t]) out.push(insertSql(dialect, t, row));
    if (dialect === 'mssql') out.push(`SET IDENTITY_INSERT ${t} OFF;`);
    out.push('');
  }
  if (dialect === 'postgres') { for (const t of TABLES) out.push(`SELECT setval(pg_get_serial_sequence('${t}', 'id'), COALESCE((SELECT max(id) FROM ${t}), 1));`); out.push('COMMIT;'); }
  if (dialect === 'mysql') out.push('SET FOREIGN_KEY_CHECKS = 1;');
  if (dialect === 'oracle') { for (const t of TABLES) out.push(`ALTER TABLE ${t} MODIFY id GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH LIMIT VALUE;`); out.push('COMMIT;'); }
  out.push('');
  return out.join('\n');
}

/* ----------------------------------------- Mongo ----------------------------------------- */

const MONGO_BSON = { id: 'long', int: 'int', bool: 'bool', date: 'string', timestamp: 'string', text: 'string', decimal: 'double' };
const bsonType = (abstract) => (abstract.startsWith('fk:') ? 'long' : MONGO_BSON[abstract] ?? 'string');

/** Colecciones con validador $jsonSchema e índices; se ejecuta con mongosh. */
export function renderSchemaMongo(database) {
  const out = ['// bot-secure: esquema genérico de pruebas (MongoDB). Colecciones: ' + TABLES.join(', ') + '.', `db = db.getSiblingDB(${JSON.stringify(database)});`, ''];
  for (const t of TABLES) {
    const props = Object.fromEntries(COLUMNS[t].map(([n, a]) => [n === 'id' ? '_id' : n, { bsonType: bsonType(a) }]));
    out.push(`if (!db.getCollectionNames().includes(${JSON.stringify(t)})) db.createCollection(${JSON.stringify(t)}, { validator: { $jsonSchema: { bsonType: "object", properties: ${JSON.stringify(props)} } } });`);
  }
  out.push('', 'db.usuarios.createIndex({ email: 1 }, { unique: true });', 'db.clientes.createIndex({ rfc: 1 });', 'db.direcciones.createIndex({ cp: 1 });', 'db.pedidos.createIndex({ cliente_id: 1 });', 'db.auditoria.createIndex({ entidad: 1, entidad_id: 1 });', '');
  return out.join('\n');
}

export function renderSeedsMongo(database, dataset, { seed, rows } = {}) {
  const out = [markerHeader('//', { seed, rows }), `// Datos SINTÉTICOS es_MX generados por bot-secure (semilla ${seed ?? '?'}).`, `db = db.getSiblingDB(${JSON.stringify(database)});`, ''];
  for (const t of TABLES) {
    const docs = dataset[t].map(({ id, ...rest }) => ({ _id: id, ...rest }));
    out.push(`db.${t}.deleteMany({});`, `db.${t}.insertMany(${JSON.stringify(docs)});`, '');
  }
  return out.join('\n');
}

/* ----------------------------------------- Redis ----------------------------------------- */

const redisArg = (v) => `"${String(v).replace(/["\\]/g, '\\$&')}"`;

/** Redis no tiene esquema: documenta el layout de claves (hash por fila + set de ids). */
export function renderSchemaRedis() {
  return ['# bot-secure: layout genérico de claves (Redis). Sin DDL: cada "tabla" es un hash por fila y un set de ids.', ...TABLES.map((t) => `#   ${t}:<id> (HASH: ${COLUMNS[t].map((c) => c[0]).join(', ')})  ·  ${t}:ids (SET)`), ''].join('\n');
}

export function renderSeedsRedis(dataset, { seed, rows } = {}) {
  const out = [markerHeader('#', { seed, rows }), `# Datos SINTÉTICOS es_MX (semilla ${seed ?? '?'}). Cargar con: grep -v '^#' seeds.redis | redis-cli -a <pw>`];
  for (const t of TABLES) {
    out.push(`DEL ${t}:ids`);
    for (const row of dataset[t]) {
      const fields = Object.entries(row).map(([k, v]) => `${k} ${redisArg(v)}`).join(' ');
      out.push(`HSET ${t}:${row.id} ${fields}`, `SADD ${t}:ids ${row.id}`);
    }
  }
  out.push('');
  return out.join('\n');
}
